CREATE TABLE shop_order (
id int(11) NOT NULL,
member_id int(11) NOT NULL,
name varchar(100) NOT NULL,
address varchar(100) NOT NULL,
mobile int(11) NOT NULL,
email varchar(100) NOT NULL,
order_status varchar(255) NOT NULL,
order_at datetime NOT NULL,
payment_type varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;